/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oocl_mob_opencvproject_NDKloader */

#ifndef _Included_com_oocl_mob_opencvproject_NDKloader
#define _Included_com_oocl_mob_opencvproject_NDKloader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oocl_mob_opencvproject_NDKloader
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oocl_mob_opencvproject_NDKloader_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_oocl_mob_opencvproject_NDKloader
 * Method:    getGrayImage
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_oocl_mob_opencvproject_NDKloader_getGrayImage
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_oocl_mob_opencvproject_NDKloader
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_oocl_mob_opencvproject_NDKloader_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
